export const skillsData = {
  cybersecurity: [
    { name: "Web Application Pentesting", percentage: 90 },
    { name: "API Security", percentage: 87 },
    { name: "Network Pentesting", percentage: 85 },
    { name: "Log Analysis", percentage: 84 },
    { name: "Endpoint Detection & Response", percentage: 82 },
    { name: "Vulnerability Assessment", percentage: 89 },
    { name: "Social Engineering Awareness", percentage: 80 },
    { name: "Security Protocols", percentage: 90 },
  ],
  technicalStack: {
    Programming: [
      "JavaScript",
      "Python",
      "Bash",
      "C",
      "C++",
      "php",
      "PowerShell",
    ],
    "Security Tools": [
      "Wireshark",
      "Nmap",
      "Burp Suite",
      "Metasploit",
      "John the Ripper",
      "Nikto",
      "Hydra",
      "Gobuster",
    ],
    "Additional Skills": [
      "OWASP Top 10",
      "CTF",
      "Bug Bounty",
      "OSINT",
      "Cloud",
      "WordPress",
      "Web Development",
      "Networking",
      "Linux",
      "Programming",
      "Artificial Intellignece",
    ],
  },
};
